Repository truecharts/library-charts, pull requests merged in 2022-05, with the labels that each got.

#51 fix(wireguard): use nft for IPTABLES
  charts/common/Chart.yaml
  charts/common/templates/addons/vpn/wireguard/_container.tpl
Labels: size/XS

#56 Fix ingressClassName middleware namespacing
  charts/common/templates/classes/_ingress.tpl
Labels: size/XS

#77 refactor serviceAccount creation
  charts/common/templates/classes/_serviceaccount.tpl
  charts/common/templates/helper/_primary-serviceAccount.tpl
  charts/common/templates/loader/_apply.tpl
  charts/common/templates/spawner/_serviceaccount.tpl
  charts/common/templates/tbd/_serviceaccount.tpl
  charts/common/values.yaml
  helper-charts/common-test/ci/rbac-values.yaml
Labels: size/M

#76 refactor RBAC creation
  charts/common/templates/classes/_rbac.tpl
  charts/common/templates/helper/_primary-rbac.tpl
  charts/common/templates/loader/_apply.tpl
  charts/common/templates/spawner/_rbac.tpl
  charts/common/templates/tbd/_rbac.tpl
  charts/common/values.yaml
  helper-charts/common-test/ci/rbac-values.yaml
Labels: size/L

#82 More TPL usage for containers and pods
  charts/common/templates/class/_configmap.tpl
  charts/common/templates/class/_ingress.tpl
  charts/common/templates/class/_networkPolicy.tpl
  charts/common/templates/class/_pvc.tpl
  charts/common/templates/class/_rbac.tpl
  charts/common/templates/class/_secret.tpl
  charts/common/templates/class/_service.tpl
  charts/common/templates/class/_serviceaccount.tpl
  charts/common/templates/lib/controller/_container.tpl
  charts/common/templates/lib/controller/_pod.tpl
  charts/common/templates/lib/controller/_ports.tpl
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/controller/_volumeMounts.tpl
  charts/common/templates/lib/controller/_volumes.tpl
  charts/common/templates/lib/dependencies/_mariadbInit.tpl
  charts/common/templates/lib/dependencies/_mongodbInit.tpl
  charts/common/templates/lib/dependencies/_postgresInit.tpl
  charts/common/templates/pods/_daemonset.tpl
  charts/common/templates/pods/_deployment.tpl
  charts/common/templates/pods/_statefulset.tpl
  charts/common/values.yaml
  tests/library/common/autoPermissions_spec.rb
Labels: size/L

#83 Ensure SCALE specific code is not run outside of SCALE
  charts/common/templates/SCALE/_externalInterfaces.tpl
  charts/common/templates/SCALE/_portal.tpl
  charts/common/templates/lib/util/_storage.tpl
  charts/common/templates/lib/values/_supplementalGroups.tpl
  charts/common/templates/spawner/_ingress.tpl
  charts/common/values.yaml
  tests/library/common/cert_spec.rb
  tests/library/common/portal_spec.rb
  tests/library/common/pvc_spec.rb
Labels: size/M

#84 Add auto-permissions support for (NFSv4) ACL's
  charts/common/templates/lib/controller/_prepare.tpl
  helper-charts/common-test/ci/persistence-values.yaml
  tests/library/common/autoPermissions_spec.rb
Labels: size/L

#87 some more work on tests
  charts/common/templates/lib/controller/_pod.tpl
  charts/common/values.yaml
  helper-charts/common-test/tests/pod/installcontainers_test.yaml
  helper-charts/common-test/tests/pod/network_test.yaml
  helper-charts/common-test/tests/pod/upgradecontainers_test.yaml
  helper-charts/common-test/tests/portal/defaults_test.yaml
  helper-charts/common-test/tests/portal/metadata_test.yaml
  helper-charts/common-test/tests/portal/nodeport_test.yaml
  helper-charts/common-test/tests/portal/overrides_test.yaml
  unittests.md
Labels: size/L
