Repository truecharts/library-charts, pull requests merged in 2022-11, with the labels that each got.

#276 chore(deps): update container image tccr.io/truecharts/multi-init to 1.1.0
  charts/common/Chart.yaml
  charts/common/values.yaml
Labels: size/XS, update/docker/general/non-major

#261 fix(common): Use correct acl binary
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
Labels: size/S

#278 fix(tailscale-addon): fix authkey and it's state, also remove the need for complex SA/RBAC
  charts/common/Chart.yaml
  charts/common/templates/addons/vpn/tailscale/_addon.tpl
  charts/common/templates/addons/vpn/tailscale/_container.tpl
  charts/common/templates/addons/vpn/tailscale/_persistence.tpl
  charts/common/templates/addons/vpn/tailscale/_rbac.tpl
  charts/common/templates/addons/vpn/tailscale/_sa.tpl
  charts/common/values.yaml
  helper-charts/common-test/tests/addons/vpn_test.yaml
Labels: size/M

#277 feat(common): add manifest updater and versioning logic
  charts/common/Chart.yaml
  charts/common/templates/lib/util/_manifest-updater.tpl
  charts/common/templates/loader/_apply.tpl
  charts/common/templates/loader/_lists.tpl
  charts/common/values.yaml
  helper-charts/common-test/ci/manifest-values.yaml
  helper-charts/common-test/values.yaml
Labels: size/L

#279 fix(auto-perms): don't try recursive on file
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/util/_crd-updater.tpl
Labels: size/XS

#286 chore(common): remove promtail and netshoot addon completely
  charts/common/Chart.yaml
  helper-charts/common-test/tests/addons/netshoot_test.yaml
Labels: size/S

#287 feat(common): add CloudNative-PG support
  charts/common/Chart.yaml
  charts/common/crds/cnpg-1.18.0.yaml
  charts/common/crds/ingressroute.yaml
  charts/common/crds/ingressroutetcp.yaml
  charts/common/crds/ingressrouteudp.yaml
  charts/common/crds/metallb-native.yaml
  charts/common/crds/middlewares.yaml
  charts/common/crds/middlewarestcp.yaml
  charts/common/crds/prometheus-crds.yaml
  charts/common/crds/serverstransports.yaml
  charts/common/crds/tlsoptions.yaml
  charts/common/crds/tlsstores.yaml
  charts/common/crds/traefikservices.yaml
  charts/common/templates/class/_pvc.tpl
  charts/common/templates/lib/controller/_container.tpl
  charts/common/templates/lib/controller/_pod.tpl
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/controller/_volumes.tpl
  charts/common/templates/lib/dependencies/_cnpgInjector.tpl
  charts/common/templates/lib/util/_crd-updater.tpl
  charts/common/templates/lib/util/_manifest-updater.tpl
  charts/common/templates/lib/util/_storage.tpl
  charts/common/templates/loader/_all.tpl
  charts/common/templates/loader/_apply.tpl
  charts/common/templates/loader/_init.tpl
  charts/common/templates/pods/_statefulset.tpl
  charts/common/templates/spawner/_configmap.tpl
  charts/common/templates/spawner/_hpa.tpl
  charts/common/templates/spawner/_ingress.tpl
  charts/common/templates/spawner/_networkPolicy.tpl
  charts/common/templates/spawner/_pvc.tpl
  charts/common/templates/spawner/_rbac.tpl
  charts/common/templates/spawner/_secret.tpl
  charts/common/templates/spawner/_service.tpl
  charts/common/templates/spawner/_serviceaccount.tpl
  charts/common/values.yaml
  helper-charts/common-test/ci/basic-values.yaml
  helper-charts/common-test/ci/cnpg-values.yaml
Labels: size/XXL

#289 fix(cnpg-common): ensure cnpg url's point to the correct pooler URLs
  charts/common/Chart.yaml
  charts/common/templates/lib/dependencies/_cnpgInjector.tpl
Labels: size/S

#293 chore(tailscale): update TS image
  charts/common/Chart.yaml
  charts/common/values.yaml
Labels: size/XS
