Repository truecharts/library-charts, pull requests merged in 2022-09, with the labels that each got.

#219 fix(ServiceAccount): fix capitalization and annotation reference
  charts/common/Chart.yaml
  charts/common/templates/class/_serviceaccount.tpl
Labels: size/XS

#220 fix(tailscale-addon): add SA, CR, CRB
  charts/common/Chart.yaml
  charts/common/templates/addons/vpn/tailscale/_addon.tpl
  charts/common/templates/addons/vpn/tailscale/_container.tpl
  charts/common/templates/addons/vpn/tailscale/_rbac.tpl
  charts/common/templates/addons/vpn/tailscale/_sa.tpl
  charts/common/values.yaml
Labels: size/M

#222 chore(deps): update container image ghcr.io/truecharts/whoami to v1.8.6
  helper-charts/common-test/ci/basic-values.yaml
  helper-charts/common-test/ci/codeserver-values.yaml
  helper-charts/common-test/ci/configmap-values.yaml
  helper-charts/common-test/ci/ingress-values.yaml
  helper-charts/common-test/ci/netshoot-values.yaml
  helper-charts/common-test/ci/networkpolicy-values.yaml
  helper-charts/common-test/ci/persistence-values.yaml
  helper-charts/common-test/ci/rbac-values.yaml
  helper-charts/common-test/ci/simple-persistence-values.yaml
  helper-charts/common-test/ci/simple-service-values.yaml
  helper-charts/common-test/values.yaml
Labels: size/S

#223 fix(tailscale): render secret
  charts/common/Chart.yaml
  charts/common/templates/addons/vpn/tailscale/_addon.tpl
  charts/common/templates/addons/vpn/tailscale/_container.tpl
Labels: size/XS

#224 chore(deps): update actions/stale digest to 99b6c70
  .github/workflows/stale.yaml
Labels: size/XS

#217 chore(deps): update renovatebot/github-action action to v32.195.5
  .github/workflows/renovate.yml
Labels: size/XS

#225 chore(deps): update renovatebot/github-action action to v32.196.0
  .github/workflows/renovate.yml
Labels: size/XS

#229 chore(deps): update actions/stale action to v6
  .github/workflows/stale.yaml
Labels: size/XS

#230 feat(/dev/shm): mount /dev/shm to memory for all containers by default
  charts/common/Chart.yaml
  charts/common/values.yaml
  helper-charts/common-test/tests/container/volumemounts_test.yaml
Labels: size/XS

#226 chore(deps): update renovatebot/github-action action to v32.202.3
  .github/workflows/renovate.yml
Labels: size/XS

#231 chore(common): remove unused variables
  charts/common/templates/class/_rbac.tpl
  charts/common/templates/class/_serviceaccount.tpl
Labels: size/XS

#232 fix(rbac): fix SA name in CRB subjects
  charts/common/Chart.yaml
  charts/common/templates/class/_rbac.tpl
  charts/common/templates/class/_serviceaccount.tpl
  charts/common/templates/lib/chart/_names.tpl
  charts/common/templates/lib/controller/_pod.tpl
  helper-charts/common-test/tests/sa-rbac/multiple_sa_rbac_test.yaml
  helper-charts/common-test/tests/sa-rbac/no sa-rbac.yaml
  helper-charts/common-test/tests/sa-rbac/sa_rbac_different_names_test.yaml
  helper-charts/common-test/tests/sa-rbac/single_sa_rbac_test.yaml
Labels: size/M

#233 chore(deps): update renovatebot/github-action action to v32.202.4
  .github/workflows/renovate.yml
Labels: size/XS

#236 bump multi-init and common
  charts/common/Chart.yaml
  charts/common/values.yaml
Labels: size/XS

#237 fix(tailscale-addon): fix indentation on includes
  charts/common/Chart.yaml
  charts/common/templates/addons/vpn/tailscale/_addon.tpl
Labels: size/XS

#241 add tests for tailscale addon
  cspell.config.yaml
  helper-charts/common-test/tests/addons/vpn_test.yaml
Labels: size/M

#240 chore(deps): update helm/chart-testing-action action to v2.3.1
  .github/workflows/charts-lint-test.yaml
Labels: size/XS
