Repository truecharts/library-charts, pull requests merged in 2022-07, with the labels that each got.

#147 fix(container): fix command list tpl
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_container.tpl
Labels: size/XS

#151 feat(clickhouse): add ClickHouse as dependency
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/controller/_probes.tpl
  charts/common/templates/lib/dependencies/_clickhouseInjector.tpl
  charts/common/templates/loader/_init.tpl
  charts/common/values.yaml
Labels: size/M

#161 Don't `b64enc` ClickHouse values
  charts/common/Chart.yaml
  charts/common/templates/lib/dependencies/_clickhouseInjector.tpl
  helper-charts/common-test/tests/persistence/volumeclaimtemplates_test.yaml
Labels: size/S

#162 feat(solr): add solr
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/dependencies/_solrInjector.tpl
  charts/common/templates/loader/_init.tpl
  charts/common/values.yaml
Labels: size/M

#163 fix(prepare): add stdout output for ClickHouse init container
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
Labels: size/XS

#165 chore(solr): add output on init
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
Labels: size/XS

#167 fix(clickhouse): Use .data instead of .stringData to retreive clickhouse password
  charts/common/Chart.yaml
  charts/common/templates/lib/dependencies/_clickhouseInjector.tpl
Labels: size/XS

#181 chore(redisinj): add plainhostpass
  charts/common/Chart.yaml
  charts/common/templates/lib/dependencies/_redisInjector.tpl
Labels: size/XS
