Repository truecharts/library-charts, pull requests merged in 2022-12, with the labels that each got.

#294 Update tailscale image
  charts/common/Chart.yaml
  charts/common/values.yaml
Labels: size/XS

#296 chore(deps): update actions/setup-python digest to 2c3dd9e
  .github/workflows/charts-lint-test.yaml
Labels: size/XS

#297 fix(common): ensure crd loader doesn't try to load non-crd objects
  .github/ct-install.yaml
  .github/workflows/charts-lint-test.yaml
  charts/common/Chart.yaml
  charts/common/crds/cnpg-1.18.0.yaml
  charts/common/crds/metallb-native.yaml
  helper-charts/common-test/ci/cnpg-values.yaml
Labels: size/XXL

#298 chore(deps): update actions/checkout digest to 7dd9e2a
  .github/workflows/charts-lint-test.yaml
  .github/workflows/common.release.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pre-commit-check.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: size/XS

#299 chore(deps): update azure/setup-helm digest to 5119fcb
  .github/workflows/charts-lint-test.yaml
  .github/workflows/common.release.yaml
Labels: size/XS

#306 feat(common): allow for rootless db-wait and cve-free autopermissions
  .github/workflows/charts-lint-test.yaml
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/util/_manifest-updater.tpl
  charts/common/values.yaml
  helper-charts/common-test/tests/pod/initcontainers_test.yaml
  helper-charts/common-test/tests/pod/installcontainers_test.yaml
  helper-charts/common-test/tests/pod/upgradecontainers_test.yaml
Labels: size/M

#307 fix(prepare): rename auto-perm container and allow to run as root - fix manifest-updater
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/util/_manifest-updater.tpl
Labels: size/XS

#308 fix(mongodb): it really wants to write on history file
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
Labels: size/XS
