Repository truecharts/library-charts, pull requests merged in 2022-10, with the labels that each got.

#245 chore(deps): update actions/checkout digest to 93ea575
  .github/workflows/charts-lint-test.yaml
  .github/workflows/common.release.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pre-commit-check.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: size/XS

#246 chore(deps): update actions/checkout digest to 2541b12
  .github/workflows/charts-lint-test.yaml
  .github/workflows/common.release.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pre-commit-check.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: size/XS

#243 fix(solr): add missing plainhost key in secret
  .github/workflows/charts-lint-test.yaml
  charts/common/Chart.yaml
  charts/common/templates/lib/controller/_prepare.tpl
  charts/common/templates/lib/dependencies/_solrInjector.tpl
Labels: size/XS

#247 fix(pvc): revert size change
  charts/common/Chart.yaml
  charts/common/templates/class/_pvc.tpl
  charts/common/values.yaml
Labels: size/XS

#242 chore(deps): update container image tccr.io/truecharts/code-server to v4.7.1
  charts/common/Chart.yaml
  charts/common/values.yaml
Labels: size/XS

#249 fix(solr): fix solr URL
  charts/common/Chart.yaml
  charts/common/templates/lib/dependencies/_solrInjector.tpl
Labels: size/XS

#250 feat(common): add improved handling of CRD updates
  charts/common/Chart.yaml
  charts/common/templates/lib/util/_crd-updater.tpl
  charts/common/templates/loader/_apply.tpl
  charts/common/values.yaml
Labels: size/M

#251 chore(deps): update actions/setup-python digest to 13ae5bb
  .github/workflows/charts-lint-test.yaml
Labels: size/XS

#253 chore(deps): update container image ghcr.io/truecharts/whoami to v1.8.7
  helper-charts/common-test/ci/basic-values.yaml
  helper-charts/common-test/ci/codeserver-values.yaml
  helper-charts/common-test/ci/configmap-values.yaml
  helper-charts/common-test/ci/ingress-values.yaml
  helper-charts/common-test/ci/netshoot-values.yaml
  helper-charts/common-test/ci/networkpolicy-values.yaml
  helper-charts/common-test/ci/persistence-values.yaml
  helper-charts/common-test/ci/rbac-values.yaml
  helper-charts/common-test/ci/simple-persistence-values.yaml
  helper-charts/common-test/ci/simple-service-values.yaml
  helper-charts/common-test/values.yaml
Labels: size/S

#255 fix(crds): fix volumeMounts name of crds
  charts/common/Chart.yaml
  charts/common/templates/lib/util/_crd-updater.tpl
Labels: size/XS

#258 chore(deps): update container image tccr.io/truecharts/multi-init to v1.0.0
  charts/common/Chart.yaml
  charts/common/values.yaml
Labels: size/XS, update/docker/general/major

#266 chore(deps): update azure/setup-helm digest to f382f75
  .github/workflows/charts-lint-test.yaml
  .github/workflows/common.release.yaml
Labels: size/XS
