Repository truecharts/library-charts, pull requests merged in 2023-04, with the labels that each got.

#373 Adds varrun emptyDir (Memory)
  library/common-test/tests/initContainer/data_test.yaml
  library/common-test/tests/initContainer/data_upgrade_test.yaml
  library/common/Chart.yaml
  library/common/values.yaml
  tools/bump.sh
Labels: size/S

#374 automatically add SETUID and SETGID when running as root, also add fl…
  library/common-test/tests/container/securityContext_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_securityContext.tpl
  library/common/values.yaml
Labels: size/L

#375 feat(common): Add Chartcontext for appurl and cidrs
  library/common-test/Chart.yaml
  library/common/Chart.yaml
  library/common/templates/lib/util/_chartcontext.tpl
  library/common/templates/loader/_init.tpl
  library/common/templates/spawner/_portal.tpl
  library/common/values.yaml
Labels: size/M

#377 Adds a check that the configmap/secret defined in persistence exists
  .github/workflows/common_library_tests.yaml
  library/common-test/tests/persistence/validation_test.yaml
  library/common-test/tests/pod/volume_configmap_test.yaml
  library/common-test/tests/pod/volume_secret_test.yaml
  library/common/templates/lib/pod/volumes/_configmap.tpl
  library/common/templates/lib/pod/volumes/_secret.tpl
  run_common_tests.sh
Labels: size/M

#376 fix(common): Chartcontextfixes
  library/common-test/Chart.yaml
  library/common/templates/lib/util/_chartcontext.tpl
  library/common/templates/spawner/_ingress.tpl
  library/common/values.yaml
Labels: size/M

#378 fix(common): correctly add persistenceList and misc fixes
  library/common-test/tests/container/env_test.yaml
  library/common-test/tests/container/volumeMounts_test.yaml
  library/common-test/tests/pod/volume_emptyDIr_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_env.tpl
  library/common/templates/lib/pod/volumes/_emptyDir.tpl
  library/common/templates/loader/_init.tpl
  library/common/templates/loader/_lists.tpl
  library/common/templates/values/lists/_persistenceList.tpl
  library/common/values.yaml
Labels: size/L

#379 fix(common): ensure serviceList is correctly parsed
  library/common-test/tests/service/list_test.yaml
  library/common/Chart.yaml
  library/common/templates/loader/_lists.tpl
  library/common/templates/values/lists/_serviceList.tpl
  library/common/values.yaml
Labels: size/M

#380 Fix endpointSlice
  library/common-test/tests/addons/netshoot_test.yaml
  library/common-test/tests/container/env_test.yaml
  library/common-test/tests/service/external_ip_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_env.tpl
  library/common/templates/lib/endpointSlice/_ports.tpl
Labels: size/S

#383 fix(common): allow for more caps when running as root and bundle the disable
  library/common-test/tests/container/securityContext_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_securityContext.tpl
  library/common/values.yaml
Labels: size/M

#384 Fix(common): default mountPath to hostPath on device type, add deviceList and set allowPrivEsca to true when privileged is true
  library/common-test/tests/container/securityContext_test.yaml
  library/common-test/tests/container/volumeMounts_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_securityContext.tpl
  library/common/templates/lib/container/_volumeMounts.tpl
  library/common/templates/loader/_lists.tpl
  library/common/templates/values/lists/_deviceList.tpl
  library/common/templates/values/lists/_persistenceList.tpl
  library/common/values.yaml
Labels: size/L

#385 Add void caps for nvidia when no gpu is selected
  library/common-test/tests/container/envFixed_test .yaml
  library/common-test/tests/initContainer/data_test.yaml
  library/common-test/tests/initContainer/data_upgrade_test.yaml
  library/common-test/tests/pod/securityContext.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_fixedEnv.tpl
  library/common/templates/lib/pod/_podSecurityContext.tpl
Labels: size/M

#386 fix(addons): Addons -> add net_raw capability, codeserver -> mark svc primary when no other exists
  library/common-test/tests/addons/codeserver_test.yaml
  library/common/Chart.yaml
  library/common/templates/addons/code-server/_codeserver.tpl
  library/common/templates/addons/code-server/_container.tpl
  library/common/templates/addons/netshoot/_container.tpl
  library/common/templates/addons/vpn/_gluetunContainer.tpl
  library/common/templates/addons/vpn/_openvpnContainer.tpl
  library/common/templates/addons/vpn/_tailscaleContainer.tpl
  library/common/templates/addons/vpn/_wireguardContainer.tpl
  library/common/values.yaml
Labels: size/M

#381 chore(deps): update actions/checkout digest to 8e5e7e5
  .github/workflows/common.release.yaml
  .github/workflows/common_library_tests.yaml
  .github/workflows/lint.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pre-commit-check.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: size/S

#382 chore(deps): update actions/checkout action to v3.5.2
  .github/workflows/renovate.yml
Labels: size/XS

#387 fix(vpn): fix configFile mountpath on wg/ovpn and give gluetun more perms and fix svcList
  library/common-test/tests/addons/vpn_test.yaml
  library/common-test/tests/service/list_test.yaml
  library/common/Chart.yaml
  library/common/templates/addons/vpn/_gluetunContainer.tpl
  library/common/templates/addons/vpn/_volume.tpl
  library/common/templates/values/lists/_serviceList.tpl
Labels: size/M

#388 fix(portList): fix port list in service
  library/common-test/tests/service/list_test.yaml
  library/common/Chart.yaml
  library/common/templates/values/lists/_portList.tpl
  library/common/templates/values/lists/_serviceList.tpl
Labels: size/M

#389 fix(resources): correctly handle "0" gpu
  library/common-test/tests/addons/vpn_test.yaml
  library/common-test/tests/container/resources_test.yaml
  library/common/Chart.yaml
  library/common/templates/addons/code-server/_container.tpl
  library/common/templates/addons/vpn/_gluetunContainer.tpl
  library/common/templates/addons/vpn/_openvpnContainer.tpl
  library/common/templates/addons/vpn/_wireguardContainer.tpl
  library/common/templates/lib/container/_resources.tpl
Labels: size/L

#390 fix(vpn,podSecContext,portal,gpu): fix wg, vpn mountpaths, portal protocol, fsGroup 0 handling, gpu
  library/common-test/tests/addons/vpn_test.yaml
  library/common-test/tests/container/envFixed_test .yaml
  library/common-test/tests/initContainer/data_test.yaml
  library/common-test/tests/initContainer/data_upgrade_test.yaml
  library/common-test/tests/pod/runtime_class_name_test.yaml
  library/common-test/tests/pod/securityContext.yaml
  library/common/Chart.yaml
  library/common/templates/addons/vpn/_openvpnContainer.tpl
  library/common/templates/addons/vpn/_volume.tpl
  library/common/templates/addons/vpn/_wireguardContainer.tpl
  library/common/templates/lib/container/_fixedEnv.tpl
  library/common/templates/lib/pod/_podSecurityContext.tpl
  library/common/templates/lib/pod/_runtimeClassName.tpl
  library/common/templates/spawner/_portal.tpl
Labels: size/L

#391 fix(portcheck,externalip): Convert everything to int for port check and fix protocol check logic for externalIP type
  library/common-test/tests/service/external_ip_test.yaml
  library/common/Chart.yaml
  library/common/templates/class/_service.tpl
  library/common/templates/helpers/_getPortRange.tpl
Labels: size/M

#392 fix(vpn): more caps for wg and gluetun
  library/common/Chart.yaml
  library/common/templates/addons/vpn/_gluetunContainer.tpl
  library/common/templates/addons/vpn/_wireguardContainer.tpl
Labels: size/XS

#393 fix(externalInterfaces): One level deeper
  library/common-test/tests/externalInterface/validation_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/externalInterface/_validation.tpl
Labels: size/M

#394 fix(gluetun): gluetun killswitch,disable GlueTun DNS and dynamic gluetun/wireguard cidr whitelist
  library/common/Chart.yaml
  library/common/templates/addons/vpn/_gluetunContainer.tpl
  library/common/templates/addons/vpn/_openvpnContainer.tpl
  library/common/templates/addons/vpn/_wireguardContainer.tpl
Labels: size/M

#395 chore(nvidia): dont allow overrides
  library/common-test/tests/container/envFixed_test .yaml
  library/common/templates/lib/container/_fixedEnv.tpl
Labels: size/S

#396 chore(deps): update actions/setup-python digest to 57ded4d
  .github/workflows/common_library_tests.yaml
Labels: size/XS

#397 chore(deps): update renovatebot/github-action action to v36.0.3
  .github/workflows/renovate.yml
Labels: size/XS

#398 fix(varrun, devshm): medium -> Memory
  library/common-test/tests/defaults/defaults-test.yaml
  library/common/Chart.yaml
  library/common/templates/class/_cronjob.tpl
  library/common/templates/class/_daemonset.tpl
  library/common/templates/class/_deployment.tpl
  library/common/templates/class/_job.tpl
  library/common/templates/class/_statefulset.tpl
  library/common/templates/lib/metadata/_selectorLabels.tpl
  library/common/templates/lib/workload/_cronjobSpec.tpl
  library/common/templates/lib/workload/_jobSpec.tpl
  library/common/values.yaml
Labels: size/M

#400 Revert a fix for endpointslice
  library/common-test/tests/service/external_ip_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/endpointSlice/_ports.tpl
Labels: size/XS

#401 chore(Endpoint): Add endpoint class and tests
  library/common-test/tests/service/external_ip_test.yaml
  library/common/Chart.yaml
  library/common/templates/class/_endpoint.tpl
  library/common/templates/class/_service.tpl
  library/common/templates/lib/endpoint/_addresses.tpl
  library/common/templates/lib/endpoint/_ports.tpl
Labels: size/L

#403 fix(endpoint): use plural for kind
  library/common-test/tests/service/external_ip_test.yaml
  library/common/Chart.yaml
  library/common/templates/class/_endpoint.tpl
Labels: size/XS

#408 fix(deps): use the correct, decrypted, credentials
  library/common-test/Chart.yaml
  library/common/Chart.yaml
  library/common/templates/lib/dependencies/_clickhouseInjector.tpl
  library/common/templates/lib/dependencies/_dbWait.tpl
  library/common/templates/lib/dependencies/_mariadbInjector.tpl
  library/common/templates/lib/dependencies/_mongodbInjector.tpl
  library/common/templates/lib/dependencies/_redisInjector.tpl
  library/common/templates/lib/dependencies/_solrInjector.tpl
Labels: size/L

#407 chore(deps): update docker general non-major
  library/common/Chart.yaml
  library/common/values.yaml
Labels: size/XS

#409 fix(manifestManager): Handle failed/completed pods before waiting for the Ready pods + increase deafult pvc size
  library/common-test/tests/persistence/pvc_data_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/util/_manifest_manager.tpl
  library/common/values.yaml
Labels: size/S

#411 fix(container/ports): fix an issue with hostNetwork toggling
  library/common-test/tests/container/ports_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_ports.tpl
Labels: size/XS

#410 chore(deps): update actions/setup-python digest to 0f07f7f
  .github/workflows/lint.yaml
Labels: size/XS

#413 chore(deps): update container image tccr.io/truecharts/tailscale to v1.40.0
  library/common/Chart.yaml
  library/common/values.yaml
Labels: size/XS
