Repository truecharts/library-charts, pull requests merged in 2023-05, with the labels that each got.

#414 chore(deps): update renovatebot/github-action action to v36.0.4
  .github/workflows/renovate.yml
Labels: size/XS

#415 chore(deps): update renovatebot/github-action action to v36.1.0
  .github/workflows/renovate.yml
Labels: size/XS

#417 chore(deps): update renovatebot/github-action action to v36.1.1
  .github/workflows/renovate.yml
Labels: size/XS

#416 fix(codeserver): don't try to mount a volume if it's target on a specific container
  library/common-test/tests/addons/codeserver_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_volumeMounts.tpl
Labels: size/M

#418 fix(checks): accept int64 as a valid int type
  .github/workflows/common_library_tests.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_probes.tpl
  library/common/templates/lib/container/_securityContext.tpl
  library/common/templates/lib/pod/_tolerations.tpl
  library/common/templates/lib/service/serviceTypeConfig/_sessionAffinity.tpl
Labels: size/S

#420 feat(common): add support for cnpg cluster hibernation without using annotations
  library/common-test/Chart.yaml
  library/common/Chart.yaml
  library/common/templates/class/_cnpgCluster.tpl
  library/common/templates/class/_cnpgPooler.tpl
  library/common/values.yaml
Labels: size/S

#422 chore(deps): update renovatebot/github-action action to v37
  .github/workflows/renovate.yml
Labels: size/XS

#423 feat(common): Add .global.stopAll option to stop all on native Helm
  library/common-test/Chart.yaml
  library/common/Chart.yaml
  library/common/templates/class/_cnpgCluster.tpl
  library/common/templates/class/_cnpgPooler.tpl
  library/common/templates/lib/pod/_nodeSelector.tpl
  library/common/templates/lib/workload/_cronjobSpec.tpl
  library/common/templates/lib/workload/_deployementSpec.tpl
  library/common/templates/lib/workload/_jobSpec.tpl
  library/common/templates/lib/workload/_statefulsettSpec.tpl
  library/common/values.yaml
Labels: size/S

#424 fix(common): cleanup stopAll changes and add some tests
  library/common-test/tests/cnpg/stop_test.yaml
  library/common-test/tests/cronjob/spec_test.yaml
  library/common-test/tests/deployment/spec_test.yaml
  library/common-test/tests/job/spec_test.yaml
  library/common-test/tests/pod/node_selector_test.yaml
  library/common-test/tests/statefulset/spec_test.yaml
  library/common/Chart.yaml
  library/common/templates/class/_cnpgCluster.tpl
  library/common/templates/class/_cnpgPooler.tpl
  library/common/templates/lib/pod/_nodeSelector.tpl
  library/common/templates/lib/workload/_cronjobSpec.tpl
  library/common/templates/lib/workload/_deployementSpec.tpl
  library/common/templates/lib/workload/_jobSpec.tpl
  library/common/templates/lib/workload/_statefulsetSpec.tpl
Labels: size/L

#426 fix(sysctls): dont add net.ipv4.ip_unprivileged_port_start when hostNet is enabled
  library/common-test/tests/pod/securityContext.yaml
  library/common/Chart.yaml
  library/common/templates/lib/pod/_podSecurityContext.tpl
Labels: size/M

#425 feat(common): implement support for registering and verifying dynamic operator namespaces
  .github/workflows/common_library_tests.yaml
  library/common-test/Chart.yaml
  library/common-test/ci/register-operator-values.yaml
  library/common-test/default-values.yaml
  library/common-test/tests/addons/codeserver_test.yaml
  library/common-test/tests/addons/netshoot_test.yaml
  library/common-test/tests/addons/vpn_test.yaml
  library/common-test/tests/configmap/metadata_test.yaml
  library/common-test/tests/defaults/defaults-test.yaml
  library/common-test/tests/operator/operator_test.yaml
  library/common-test/tests/secret/metadata_test.yaml
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/class/_configmap.tpl
  library/common/templates/class/_secret.tpl
  library/common/templates/lib/util/_register_operator.tpl
  library/common/templates/lib/util/_tc_namespace.tpl
  library/common/templates/lib/util/_verify_operator.tpl
  library/common/templates/loader/_init.tpl
  library/common/values.yaml
Labels: size/L

#427 chore(deps): update docker general non-major
  library/common/Chart.yaml
  library/common/values.yaml
Labels: size/XS

#428 feat(common): add hostPID support
  library/common-test/tests/defaults/defaults-test.yaml
  library/common-test/tests/pod/host_pid_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/pod/_hostPID.tpl
  library/common/templates/lib/workload/_pod.tpl
Labels: size/M

#429 fix(tailscale): needs SA token
  library/common-test/tests/addons/vpn_test.yaml
  library/common/Chart.yaml
  library/common/templates/addons/vpn/_tailscaleContainer.tpl
  library/common/templates/addons/vpn/_vpn.tpl
Labels: size/S

#431 feat(common): add support for shareProcessNamespace
  library/common-test/Chart.yaml
  library/common-test/tests/defaults/defaults-test.yaml
  library/common-test/tests/ingress/metadata_test.yaml
  library/common-test/tests/pod/share_process_namespace_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/pod/_shareProcessNamespace.tpl
  library/common/templates/lib/workload/_pod.tpl
  library/common/values.yaml
Labels: size/M

#433 fix(tailscale): run rootless and switch state dir to subdir of the emptyDir
  library/common-test/tests/addons/vpn_test.yaml
  library/common/Chart.yaml
  library/common/templates/addons/vpn/_tailscaleContainer.tpl
  library/common/templates/addons/vpn/_volume.tpl
  library/common/templates/addons/vpn/_vpn.tpl
Labels: size/M

#430 fix(Common): Fix ingress typo
  library/common/templates/class/_ingress.tpl
  library/common/templates/class/_route.tpl
Labels: size/XS

#436 chore(typo): Fix file name typo and remove a line from comments
  library/common/templates/lib/workload/_daemonsetSpec.tpl
  library/common/templates/lib/workload/_deploymentSpec.tpl
Labels: size/XS

#437 fix(common): reenable manifest manager and add deletion logic
  library/common-test/ci/register-operator-values.yaml
  library/common/Chart.yaml
  library/common/templates/lib/util/_manifest_manager.tpl
  library/common/values.yaml
Labels: size/S

#438 chore(ndots): default to 1
  library/common-test/tests/defaults/defaults-test.yaml
  library/common/Chart.yaml
  library/common/values.yaml
Labels: size/XS

#439 fix(common): use pre-install hook for `tc-system` namespace creation
  library/common/Chart.yaml
  library/common/templates/lib/util/_tc_namespace.tpl
Labels: size/XS

#440 fix(operators): update logic for verifying and registering
  library/common-test/tests/operator/operator_test.yaml
  library/common/templates/lib/util/_register_operator.tpl
  library/common/templates/lib/util/_tc_namespace.tpl
  library/common/templates/lib/util/_verify_operator.tpl
  library/common/templates/loader/_init.tpl
Labels: size/M

#442 fix: remove tc-system namespace creation and fix operator verification code
  library/common-test/default-values.yaml
  library/common-test/tests/defaults/defaults-test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/util/_tc_namespace.tpl
  library/common/templates/lib/util/_verify_operator.tpl
  library/common/templates/loader/_init.tpl
  library/common/values.yaml
Labels: size/M

#443 feat(common): tweak operator verification behavior
  library/common-test/values.yaml
  library/common/Chart.yaml
  library/common/templates/lib/util/_verify_operator.tpl
  library/common/values.yaml
Labels: size/XS

#444 feat(common): fix operator verify values.yaml input and add caching
  library/common/templates/lib/util/_verify_operator.tpl
Labels: size/M
