Repository truecharts/library-charts, pull requests merged in 2023-02, with the labels that each got.

#254 Update EndBug/label-sync digest to da00f2c
  .github/workflows/schedule-sync-labels.yaml
Labels: size/XS

#239 chore(deps): update helm/chart-releaser-action action to v1.5.0
  .github/workflows/common.release.yaml
Labels: size/XS

#235 chore(deps): update renovatebot/github-action action to v32.241.11
  .github/workflows/renovate.yml
Labels: size/XS

#244 chore(deps): update actions/checkout action
  .github/workflows/lint.yaml
  .github/workflows/renovate.yml
Labels: size/XS

#263 chore(deps): update renovatebot/github-action action to v34
  .github/workflows/renovate.yml
Labels: size/XS

#320 chore(deps): update docker general non-major
  library/common/values.yaml
Labels: size/XS

#328 feat(common): readd deprecated wireguard and openvpn containers for backwards compatibility
  .github/workflows/common_library_tests.yaml
  library/common-test/Chart.yaml
  library/common-test/ci/vpn-openvpn-values.yaml
  library/common-test/ci/vpn-wireguard-values.yaml
  library/common-test/tests/addons/vpn_test.yaml
  library/common/Chart.yaml
  library/common/templates/addons/vpn/_openvpnContainer.tpl
  library/common/templates/addons/vpn/_vpn.tpl
  library/common/templates/addons/vpn/_wireguardContainer.tpl
  library/common/values.yaml
Labels: size/L

#329 feat(common): allow postgres -> cnpg migration
  library/common-test/Chart.yaml
  library/common/Chart.yaml
  library/common/templates/class/_cnpgCluster.tpl
  library/common/templates/spawner/_cnpg.tpl
Labels: size/S

#327 chore(deps): pin dependencies
  .github/workflows/common_library_tests.yaml
  .github/workflows/lint.yaml
Labels: size/XS

#330 chore(deps): update docker general non-major
  library/common/values.yaml
Labels: size/XS, update/docker/general/non-major

#331 chore(deps): update renovatebot/github-action action to v34.153.2
  .github/workflows/renovate.yml
Labels: size/XS

#319 chore(deps): update actions/setup-python digest to d27e3f3
  .github/workflows/common_library_tests.yaml
Labels: size/XS

#317 chore(deps): update actions/checkout digest to ac59398
  .github/workflows/common.release.yaml
  .github/workflows/common_library_tests.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pre-commit-check.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: size/S

#333 chore(deps): update container image tccr.io/truecharts/wget to v1.0.0
  library/common/values.yaml
Labels: size/XS, update/docker/general/major

#321 chore(deps): update container image tccr.io/truecharts/db-wait-mariadb to v1.1.0
  library/common/values.yaml
Labels: size/XS

#322 chore(deps): update container image tccr.io/truecharts/db-wait-mongodb to v1.1.0
  library/common/values.yaml
Labels: size/XS

#332 chore(deps): update container image tccr.io/truecharts/db-wait-redis to v1.1.0
  library/common/values.yaml
Labels: size/XS

#326 chore(deps): update container image tccr.io/truecharts/db-wait-postgres to v1.1.0
  library/common/values.yaml
Labels: size/XS

#334 chore(deps): update azure/setup-helm digest to 5119fcb
  .github/workflows/common_library_tests.yaml
Labels: size/XS
