Repository truecharts/library-charts, pull requests merged in 2023-06, with the labels that each got.

#448 feat(common): add support for additional templates defined in values.yaml
  library/common-test/Chart.yaml
  library/common-test/tests/defaults/defaults-test.yaml
  library/common-test/tests/extraTpl/extratpl_test.yaml
  library/common/Chart.yaml
  library/common/templates/loader/_apply.tpl
  library/common/templates/spawner/_extraTpl.tpl
  library/common/values.yaml
Labels: size/M

#450 Label fix
  library/common-test/tests/certificate/metadata_test.yaml
  library/common-test/tests/configmap/metadata_test.yaml
  library/common-test/tests/cronjob/metadata_test.yaml
  library/common-test/tests/daemonset/metadata_test.yaml
  library/common-test/tests/defaults/defaults-test.yaml
  library/common-test/tests/deployment/metadata_test.yaml
  library/common-test/tests/imagePullSecret/metadata_test.yaml
  library/common-test/tests/ingress/metadata_test.yaml
  library/common-test/tests/job/metadata_test.yaml
  library/common-test/tests/persistence/metadata_test.yaml
  library/common-test/tests/rbac/metadata_test.yaml
  library/common-test/tests/secret/metadata_test.yaml
  library/common-test/tests/service/external_ip_test.yaml
  library/common-test/tests/serviceAccount/metadata_test.yaml
  library/common-test/tests/statefulset/metadata_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/metadata/_allLabels.tpl
  library/common/templates/lib/metadata/_render.tpl
Labels: size/M

#451 Add chmod to auto perm script
  library/common-test/tests/initContainer/autoperms_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/util/_autoperms.tpl
Labels: size/L

#445 chore(deps): update container image tccr.io/truecharts/tailscale to v1.42.0
  library/common/values.yaml
Labels: size/XS

#432 chore(deps): update actions/setup-python digest to bd6b4b6
  .github/workflows/common_library_tests.yaml
Labels: size/XS
