Repository truecharts/library-charts, pull requests merged in 2023-03, with the labels that each got.

#335 chore(deps): update renovatebot/github-action action to v34.154.1
  .github/workflows/renovate.yml
Labels: size/XS

#339 add tests
  library/common-test/tests/initContainer/data_test.yaml
  library/common-test/tests/initContainer/data_upgrade_test.yaml
Labels: size/M

#336 chore(deps): update docker general non-major
  library/common/values.yaml
Labels: size/XS

#340 add NET_BIND_SERVICE on ports <1024
  library/common-test/tests/container/ports_test.yaml
  library/common-test/tests/secret/validation_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_securityContext.tpl
Labels: size/S

#338 chore(deps): update renovatebot/github-action action to v34.157.0
  .github/workflows/renovate.yml
Labels: size/XS

#342 feat(common): allow tpl for env expandObjectName, configmap-name and secret-name
  library/common/Chart.yaml
  library/common/templates/lib/container/_env.tpl
  library/common/templates/lib/container/_envFrom.tpl
  library/common/templates/spawner/_configmap.tpl
  library/common/templates/spawner/_secret.tpl
Labels: size/S

#344 feat(cnpg): add postgresql section for custom config
  library/common-test/tests/cnpg/custom_conf_test.yaml
  library/common/Chart.yaml
  library/common/templates/class/_cnpgCluster.tpl
  library/common/values.yaml
Labels: size/S

#343 fix(common): allow 2 letters names
  library/common-test/tests/configmap/validation_test.yaml
  library/common-test/tests/container/envFixed_test .yaml
  library/common-test/tests/container/envFrom_test.yaml
  library/common-test/tests/container/env_test.yaml
  library/common-test/tests/initContainer/data_test.yaml
  library/common-test/tests/initContainer/data_upgrade_test.yaml
  library/common-test/tests/secret/validation_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/chart/_names.tpl
  library/common/templates/lib/container/_env.tpl
  library/common/templates/lib/container/_envFrom.tpl
  library/common/templates/lib/pod/_initContainerSpawner.tpl
  library/common/templates/spawner/_configmap.tpl
  library/common/templates/spawner/_secret.tpl
Labels: size/M

#346 Fix VCT issues
  library/common/Chart.yaml
  library/common/templates/class/_statefulset.tpl
  library/common/templates/lib/storage/_volumeClaimTemplates.tpl
Labels: size/XS

#345 chore(deps): update renovatebot/github-action action to v34.157.1
  .github/workflows/renovate.yml
Labels: size/XS

#347 fix(service): adapt code to not fail with a helm version without shor…
  library/common-test/tests/volumeClaimTemplate/metadata_test.yaml
  library/common/Chart.yaml
  library/common/templates/class/_service.tpl
Labels: size/S

#348 feat(common): allow for tpl/string for cnpg enable
  library/common/Chart.yaml
  library/common/templates/spawner/_cnpg.tpl
Labels: size/S

#351 fix(common): prevent random nodePorts being assigned for LoadBalancer
  library/common/Chart.yaml
  library/common/templates/lib/service/serviceTypeSpecs/_loadBalancer.tpl
Labels: size/XS

#352 scan all values for helm produced errors for yaml
  library/common-test/tests/service/load_balancer_test.yaml
  library/common-test/tests/service/metadata_test.yaml
  library/common/Chart.yaml
  library/common/templates/loader/_apply.tpl
  library/common/templates/values/_validate.tpl
Labels: size/S

#353 chore(deps): update actions/cache digest to 940f3d7
  .github/workflows/common_library_tests.yaml
Labels: size/XS

#350 chore(deps): update renovatebot/github-action action to v34.159.2
  .github/workflows/renovate.yml
Labels: size/XS

#354 chore(deps): update renovatebot/github-action action to v35
  .github/workflows/renovate.yml
Labels: size/XS

#355 chore(validation): update name validation regex, to not allow `--`
  library/common/Chart.yaml
  library/common/templates/lib/chart/_names.tpl
Labels: size/XS

#356 chore(deps): update renovatebot/github-action action to v35.1.2
  .github/workflows/renovate.yml
Labels: size/XS

#357 chore(deps): update renovatebot/github-action action to v35.2.0
  .github/workflows/renovate.yml
Labels: size/XS

#358 chore(deps): update actions/cache digest to 88522ab
  .github/workflows/common_library_tests.yaml
Labels: size/XS

#359 chore(deps): update renovatebot/github-action action to v36
  .github/workflows/renovate.yml
Labels: size/XS

#361 chore(deps): update actions/checkout digest to 24cb908
  .github/workflows/common.release.yaml
  .github/workflows/common_library_tests.yaml
  .github/workflows/lint.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pre-commit-check.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: size/S

#362 chore(deps): update actions/checkout action to v3.4.0
  .github/workflows/renovate.yml
Labels: size/XS

#365 fix(common): disable removing port due to iX bug
  library/common/Chart.yaml
  library/common/templates/spawner/_portal.tpl
Labels: size/XS

#367 chore(deps): update actions/stale action to v8
  .github/workflows/stale.yaml
Labels: size/XS

#368 chore(deps): update actions/checkout digest to 8f4b7f8
  .github/workflows/common.release.yaml
  .github/workflows/common_library_tests.yaml
  .github/workflows/lint.yaml
  .github/workflows/metadata-label-commenter.yaml
  .github/workflows/pre-commit-check.yaml
  .github/workflows/renovate-bump.yaml
  .github/workflows/schedule-sync-labels.yaml
Labels: size/S

#369 chore(deps): update actions/checkout action to v3.5.0
  .github/workflows/renovate.yml
Labels: size/XS

#370 chore(deps): update helm/chart-testing-action action to v2.4.0
  .github/workflows/common_library_tests.yaml
Labels: size/XS

#371 chore(deps): update renovatebot/github-action action to v36.0.2
  .github/workflows/renovate.yml
Labels: size/XS

#372 Add CHOWN cap when runnign as root, as its needed 99% of the time
  library/common-test/tests/container/securityContext_test.yaml
  library/common/Chart.yaml
  library/common/templates/lib/container/_securityContext.tpl
Labels: size/S
